cd: add automatic docker installation and app folder creation

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -53,6 +53,21 @@ jobs:
           port: ${{ secrets.SSH_PORT }}
           script: |
             set -e
+
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing Docker..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sudo sh get-docker.sh
+              sudo usermod -aG docker $USER
+              
+              sudo chmod 666 /var/run/docker.sock
+              echo "Docker successfully installed!" 
+            else
+              echo "Docker already installed, skipping this step."
+            fi
+
+            mkdir -p ${{ secrets.SSH_TARGET_DIR }}
+
             cd ${{ secrets.SSH_TARGET_DIR }}
 
             echo "${{ secrets.PROD_ENV_FILE }}" > .env
